version: "3.7"

services:
  sistema_gestao:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sistema-getao-network
    depends_on:
      - postgres

  nginx:
    container_name: servidor-nginx-v2
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - sistema-getao-network

  postgres:
    container_name: banco-postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    networks:
      - sistema-getao-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8899:8080
    networks:
      - sistema-getao-network

networks:
  sistema-getao-network:
    driver: bridge
